os: ubuntu
language: node_js
node_js:
- 0.12.7
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_452995f7b481_key -iv $encrypted_452995f7b481_iv
  -in .travis/hexo_rsa.enc -out ～/.ssh/hexo_rsa -d
- chmod 600 ~/.ssh/hexo_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/hexo_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "czy1121"
- git config --global user.email 249736246@qq.com
install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
