before_install:
language: node_js
node_js:
 - "0.12.7"
branches:
  only:
  - hexo
before_install:
 # Decrypt the private key
 - openssl aes-256-cbc -K $encrypted_452995f7b481_key -iv $encrypted_452995f7b481_iv -in .travis/reezy_blog_rsa.enc -out ～/.ssh/id_rsa -d
 # Set the permission of the key
 - chmod 600 ~/.ssh/id_rsa
 # Start SSH agent
 - eval $(ssh-agent)
 # Add the private key to the system
 - ssh-add ~/.ssh/id_rsa
 # Copy SSH config
 - cp .travis/ssh_config ~/.ssh/config
 # Set Git config
 - git config --global user.name "czy1121"
 - git config --global user.email 249736246@qq.com
install:
 - npm install hexo-cli -g
 - npm install hexo --save
 - npm install
script:
 - hexo clean
 - hexo generate
 - hexo deploy