language: node_js
node_js:
- 0.12.7
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_452995f7b481_key -iv $encrypted_452995f7b481_iv
  -in .travis/hexo_rsa.enc -out ~/.ssh/hexo_rsa -d
- chmod 600 ~/.ssh/hexo_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/hexo_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "czy1121"
- git config --global user.email 249736246@qq.com
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install
script:
- hexo clean
- hexo generate
- hexo deploy
env:
  global:
    secure: YhIe6wFcFIFuqX1tDueX06F7qLgd055kHgdjQe+BcvDJKi/n9myshFqRVzGSbZ3BCkWB7MUBDNzXFmKKeUh5lLaZtEh7KF46043uvbq+pO/tECm3qQJc7EW0ZzQTTlwjBSkVi6vuooTg3O8P+z3IgU6bmc6A3a+VzHs+lnA/xckBlUL8eQpJzE5Odoo6TnplFRh+hg+HmpRlkOQjdibX8KCtxT0A7xIek+3hvhWBNtFq8QPtaly7X1053RzgoBhyKF54OACIUr1SDwbyg7o3aVZPwZTgAvewJ+etp4lktsLbDID21e/LW2yFobBx9q6Ck918B6SxlJ4xsfApAEmDaeFtuONeY45a7T+2eDR0nDaA/+Zy02mO3R+D/0ECE3FTBoSFXou/xUj+QwshgKmNWNBWXW29mD54BPw+8ToWu93FToaMST8nF6qWAom6MWkm7+onPqbtPwOYhTXAD0dn8ZzDAIOFfex8o6HdcsjdEZ8AurLpmm0duXPZTrh4xXGkZRyZkm1yy6lv1mSQnzMLb5rftdXOUsHaeTSgGFjoc+q/5dvNmdVzTwUEEkjL2bHtBqQafamSCAs0LS6Ml/TfhyiAo9MolbCDzXd6rNSTvlwrUG9U2NtLf/VAKUUVJbXpvqv2aDm8bEdZMgkb89I8LFtu/r6KOoUqMbyUsV/WSjA=
